#################################################################################################################
#image: docker
image: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest

#services:
#  - git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:browserstacklocal
#image:
#  name: git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest
#  entrypoint: ["nohup ./BrowserStackLocal --key=c8EHLyzv9zWTJ2zGRedY --force-local --local-identifier=AutomationTest2 > output.out 2>&1 &"]

#run the browserstack local container
#services:
#  - git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:browserstacklocal

#################################################################################################################
before_script:
  - echo "this is the before_script in action - will install frameworks' plugins"
#  - ls -al
#linux version  : both below work
#  - cat /etc/os-release
#  - uname -r
#  - /bin/bash







######### BROWSER STACK LOCAL ########
# Start BrowserStackLocal and wait for 10 seconds for the tunnel to come up
#----------------->  the one below is not getting/reading the value of the ${BROWSERSTACK_LOCAL_KEY}
#  - nohup ./BrowserStackLocal --key ${BROWSERSTACK_LOCAL_KEY} --force-local --local-identifier AutomationTest2 > output.out 2>&1 &

#----------------->  the one below works perfectly ---was / once only
#  - nohup ./BrowserStackLocal --key=c8EHLyzv9zWTJ2zGRedY --force-local --local-identifier=AutomationTest2 > output.out 2>&1 & #this works if I run the local container and in bash this command
#  - sleep 10







  - npm install
#  - echo "expected docker image to be up, browserstacklocal as well - tst env is ready for running the tests"
  - echo



#################################################################################################################
stages:
  - tests_run_automated   #stage for the automated jobs only
  - tests_run_manual      #stage for the manual jobs only
  - docker_build_and_push #stage for re-building & pushing the docker image --- THIS STAGE IS NOT WORKING YET - NEEDS TO BE CREATED & TESTED


#################################################################################################################
# running 2 groups of automated jobs as we have the ability to have 2 parallel runs within BrowserStack
autoRun_Group1:
  stage: tests_run_automated
  script:
    - echo "automated test run -------------------------------------------------------------------------------------"
#    - ./BrowserStackLocal --key c8EHLyzv9zWTJ2zGRedY --force-local --local-identifier=AutomationTest1
    - npm run generic:CreateABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:CreateEditDeleteABasicPage -- --env=tst --appName=ucLaw --browserStack=true

# --- below there are more examples of running tests (with & without GitLab Variables):
#    - ${npm_run_test}
#    - npm run uclaw:test1 -- --env=tst --appName=ucLaw --browserStack=true
#    - npm run ${testName} -- --env=tst --appName=ucLaw --browserStack=true --browserStackArgs=${browserStackArgs1}
#    - npm run ${testName} -- --env=${env} --appName=ucLaw --browserStack=true  #this also works
#    - npm run generic:ValidateInternalMenuAsSiteAdmin -- --env=tst --appName=ucLaw --browserStack=true --browserStackArgs=Windows,10,Chrome,69.0,1920x1080
#    - echo

#  when: manual
  allow_failure: false

  only:
    - master

#  artifacts:
#    reports:
#      junit: rspec.xml
#      junit: ${testName}.xml

  environment:  # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
autoRun_Group2:
  stage: tests_run_automated
  script:
    - echo "automated test run -------------------------------------------------------------------------------------"
    - npm run generic:AllUserRolesLoginLogoutSuccessfully -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:ValidateInternalMenuAsSiteAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:ValidateInternalMenuAsContentAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddTextHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddAccordionToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

#  when: manual
  allow_failure: false

  only:
    - master

#  artifacts:
#    reports:
#      junit: rspec.xml

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca



#################################################################################################################
1.Build_Docker_Image:
  stage: docker_build_and_push
  script:
    - echo "build docker image if automated tests are passed -------------------------------------------------------"
    - echo "nothing yet - not done"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker info
#    - docker build --no-cache -t git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest .
#    - if [ -n "${UPLOAD_TO_S3}" ]; then make upload; fi
    - echo

  when: manual
  allow_failure: false

  only:
    - master

#################################################################################################################
2.Push_Docker_Image:
  stage: docker_build_and_push
  script:
    - echo "push docker image if docker image was built ------------------------------------------------------------"
    - echo "nothing yet - not done"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#    - docker push git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest .
#    - if [ -n "${Build_Docker_Image}" ]; then make upload; fi
    - echo

  when: manual
  allow_failure: false

  only:
    - master

#################################################################################################################
3.Docker_Image_Test:
  stage: docker_build_and_push
  script:
    - echo "run a small test to check the build docker image works -------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master



#################################################################################################################
# THE INTENTION OF THE BELOW JOBS / RUNS ARE FOR ALL THE AVAILABLE TESTS TO BE RUN MANUALLY ONE BY ONE
#################################################################################################################
CreateABasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:CreateABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  #  allow_failure: false
  allow_failure: true

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

CreateEditDeleteABasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:CreateEditDeleteABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  #  allow_failure: false
  allow_failure: true

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddHeroCTAToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: true #false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddTextHeroCTAToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddTextHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: true #false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddAccordionToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddAccordionToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: true #false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AllUserRolesLoginLogoutSuccessfully:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AllUserRolesLoginLogoutSuccessfully -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: true #false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
ValidateInternalMenuAsSiteAdmin:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsSiteAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
#  allow_failure: false
  allow_failure: true

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
ValidateInternalMenuAsContentAdmin:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: true #false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
ValidateInternalMenuAsContentEditor:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: true #false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca



#################################################################################################################



after_script:
  - echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tests run done ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"