#image: docker
image: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest

before_script:
  - echo "this is the before_script in action"
  - npm install
  #  - ls -al $PWD
  - echo "expected docker image to be up - tst env should be ready for tests"
  - echo

stages:
#- build_automated_env
- run_automated_tests

#job_build_automated_env:
#  stage: build_automated_env
#  image: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest
#  script:
#  - npm install
#  - echo "expected docker image to be up - tst env should be ready for tests"

test1:
  stage: run_automated_tests
  script:
  - echo "run test 1 ------------------------------------------------------------------------------------------"
  - echo "npm run ${testName} -- --env=${env} --browserStack=true --browserStackArgs=${browserStackArgs1}"
#  - echo "npm run "${testName}" -- --env="${env}" --browserStack=true --browserStackArgs="${browserStackArgs1}""
  - npm run ${testName} -- --env=${env} --browserStack=true --browserStackArgs=${browserStackArgs1}
#  - npm run "${testName}" -- --env="${env}" --browserStack=true  #this also works
  - echo

  when: manual
  allow_failure: false

  only:
  - master      # the test/job will run only in master branch

  artifacts:
    reports:
      junit: rspec.xml
#      junit: ${testName}.xml

  environment:  # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca


test2:
  stage: run_automated_tests
  script:
  - echo "run test 2 ------------------------------------------------------------------------------------------"
  - echo "${npm_run_test}"
  - ${npm_run_test}
  - echo

  when: manual
  allow_failure: false

  only:
  - master      # the test/job will run only in master branch

  artifacts:
    reports:
      junit: rspec.xml

  environment:  # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca


#test2:
#  stage: run_automated_tests
#  script:
#  - echo "run test 2 ------------------------------------------------------------------------------------------"
#  - echo "${npm_run_test}"
#  - ${npm_run_test}
#  - echo
#
#test3:
#  stage: run_automated_tests
#  script:
#  - echo "run test 3 ------------------------------------------------------------------------------------------"
#  - ${npm_run_test_with_vars}
#  - echo


after_script:
  - echo "tests run done"