#################################################################################################################
#image: docker
image: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest

#################################################################################################################
before_script:
  - echo "this is the before_script in action - will install frameworks' plugins"
  - npm install
  - echo


#################################################################################################################
stages:
  - tests_run_automated   #stage for the automated jobs only
  - tests_run_manual      #stage for the manual jobs only
  - docker_build_and_push #stage for re-building & pushing the docker image --- THIS STAGE IS NOT WORKING YET - NEEDS TO BE CREATED & TESTED


#################################################################################################################
# running 2 groups of automated jobs as we have the ability to have 2 parallel runs within BrowserStack
autoRun_Group1:
  image: git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing
  stage: tests_run_automated
  script:
    - echo "automated test run -------------------------------------------------------------------------------------"
    - npm run generic:CreateABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:CreateEditDeleteABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddTextToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddImageToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddImageWithTextToBasicPage -- --env=tst --appName=ucLaw --browserStack=true

  when: manual
  allow_failure: false

  only:
    - master

  environment:  # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
autoRun_Group2:
  image: git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing
  stage: tests_run_automated
  script:
    - echo "automated test run -------------------------------------------------------------------------------------"
    - npm run generic:AddHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddTextHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddAccordionToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddBannerToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddChecklistToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddMoreInfoToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AddSidekickToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:AllUserRolesLoginLogoutSuccessfully -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:ValidateInternalMenuAsSiteAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:ValidateInternalMenuAsContentAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca



#################################################################################################################
1.Build_Docker_Image:
  stage: docker_build_and_push
  script:
    - echo "build docker image if automated tests are passed -------------------------------------------------------"
    - echo "nothing yet - not done"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
    - docker info
#    - docker build --no-cache -t git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest .
#    - if [ -n "${UPLOAD_TO_S3}" ]; then make upload; fi
    - echo

  when: manual
  allow_failure: false

  only:
    - master

#################################################################################################################
2.Push_Docker_Image:
  stage: docker_build_and_push
  script:
    - echo "push docker image if docker image was built ------------------------------------------------------------"
    - echo "nothing yet - not done"
    - echo "$REGISTRY_PASSWORD" | docker login -u "$REGISTRY_USER" --password-stdin
#    - docker push git.caas.ucalgary.ca:4567/ws/drupal8/qa/automation-testing:latest .
#    - if [ -n "${Build_Docker_Image}" ]; then make upload; fi
    - echo

  when: manual
  allow_failure: false

  only:
    - master

#################################################################################################################
3.Docker_Image_Test:
  stage: docker_build_and_push
  script:
    - echo "run a small test to check the build docker image works -------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master



#################################################################################################################
# THE INTENTION OF THE BELOW JOBS / RUNS ARE FOR ALL THE AVAILABLE TESTS TO BE RUN MANUALLY ONE BY ONE
#################################################################################################################
CreateABasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:CreateABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false
#  allow_failure: true

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
CreateEditDeleteABasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:CreateEditDeleteABasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddHeroCTAToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddTextHeroCTAToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddTextHeroCTAToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddAccordionToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddAccordionToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddBannerToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddBannerToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddChecklistToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddChecklistToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddMoreInfoToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddMoreInfoToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddSidekickToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddSidekickToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddTextToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddTextToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddImageToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddImageToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AddImageWithTextToBasicPage:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AddImageWithTextToBasicPage -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
AllUserRolesLoginLogoutSuccessfully:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:AllUserRolesLoginLogoutSuccessfully -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
ValidateInternalMenuAsSiteAdmin:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsSiteAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
ValidateInternalMenuAsContentAdmin:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentAdmin -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################
ValidateInternalMenuAsContentEditor:
  stage: tests_run_manual
  script:
    - echo "manual test run -------------------------------------------------------------------------------------"
    - npm run generic:ValidateInternalMenuAsContentEditor -- --env=tst --appName=ucLaw --browserStack=true
    - echo

  when: manual
  allow_failure: false

  only:
    - master      # the test/job will run only in master branch

  environment:    # not sure what the one below does - is it needed?!
    name: ${env}
    url: https://law-tst.ucalgary.ca

#################################################################################################################



after_script:
  - echo "^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ tests run done ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^"