image: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest

services:
- name: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest
  alias: ucautomation

before_script:
  - echo "this is the before_script in action"
  - npm install
  - echo "npm install should be done"
#  - ls -al $PWD
  - echo

stages:
- build_automated_env
- run_automated_tests

job_build_automated_env:
  stage: build_automated_env
#  image: ucautomation
  image: git.caas.ucalgary.ca:4567/valeriu.jecov/ucautomation:latest
  script:
  - docker-compose up
  - echo "expected dockercompose to be up - tst env should be ready for tests"

job_run_automated_test1:
  stage: run_automated_tests
  script:
  - echo "run test 1 ------------------------------------------------------------------------------------------"
  - npm run uclaw:test1 -- --env=tst --browserStack=true

job_run_automated_test2:
  stage: run_automated_tests
  script:
  - echo "run test 2 ------------------------------------------------------------------------------------------"
  - npm run "${testName}" -- --env="${env}" --browserStack=true

# not sure what the one below does - is it needed?!
  environment:
    name: law-tst
    url: https://law-tst.ucalgary.ca

  when: manual

  allow_failure: false

  #will run only in master branch
  only:
  - master

  after_script:
  - echo "tests run done"
